"""Add rate_limit_configs table

Revision ID: 0012_add_rate_limit_configs
Revises: f8g9h0i1j2k3
Create Date: 2026-06-30 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '0012_add_rate_limit_configs'
down_revision = 'f8g9h0i1j2k3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'rate_limit_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('endpoint_type', sa.String(length=50), nullable=False),
        sa.Column('limit_value', sa.String(length=50), nullable=False),
        sa.Column('requests_per_period', sa.Integer(), nullable=False),
        sa.Column('period_seconds', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('modified_by', sa.String(length=255), nullable=True),
        sa.Column('modified_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_configs_endpoint_type'), 'rate_limit_configs', ['endpoint_type'], unique=True)
    
    # Insert default rate limits
    op.execute(
        """
        INSERT INTO rate_limit_configs (endpoint_type, limit_value, requests_per_period, period_seconds, description, enabled, modified_by)
        VALUES
            ('auth', '10/minute', 10, 60, 'Authentication endpoints (brute force protection)', true, 'system_init'),
            ('read', '150/minute', 150, 60, 'GET operations (less risky)', true, 'system_init'),
            ('write', '50/minute', 50, 60, 'POST/PUT operations', true, 'system_init'),
            ('heavy', '5/minute', 5, 60, 'Heavy operations (ML, universe scan)', true, 'system_init'),
            ('general', '100/minute', 100, 60, 'General endpoints', true, 'system_init'),
            ('search', '30/minute', 30, 60, 'Search/filter operations', true, 'system_init')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_configs_endpoint_type'), table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    # ### end Alembic commands ###
